### ISSUE TITLE
Upload issue

### ISSUE THREAD

**Issue by 3dproduction** [Sayduck/sayduck-platform-feedback#12]
Hi,
Whenever we are trying to upload a new mesh in existing project, It takes too much time, and in the end it doesn't gets upload on platform.
I've attached screenshot for this.
Please help what should we do, and if we are doing something wrong please advice.

Thank you.
![image](https://user-images.githubusercontent.com/87762015/127165837-415b620e-a186-440c-83f5-4827bda15658.png)

**Comment by JoelSayduck** [comment]
Hi,

Could you send me the file you are trying to upload?

I would assume this has to do with the 3D structure since we have only experienced issues upload CAD models. You should check the all stacked vertices are welded.

**Comment by colesnicGreg** [comment]
Seems like the file was uploading on an empty product, but not on an existing product, especially the FBX format.

**Comment by 3dproduction** [comment]
Hi, 
Actually we are uploading OBJ, Still that issue is coming.

**Comment by colesnicGreg** [comment]
Please share the obj and fbx file with Joel
