### ISSUE TITLE
AO issue in Preview link on desktop 

### ISSUE THREAD

**Issue by gabrielekraujelyte** [Sayduck/sayduck-platform-feedback#13]
Ambient occlusion map placement is off in product preview, see the screenshot attached. 
![image](https://user-images.githubusercontent.com/42536074/127287983-0806d9d3-b1cc-4948-bb6b-28e6c86e6445.png)
It looks correct in Editor, see the screenshot attached.
![image](https://user-images.githubusercontent.com/42536074/127288059-2e3c33fe-9ad2-4ec3-b466-fa8aa3325117.png)

Editor link: https://platform.sayduck.com/editor/UHJvZHVjdC0zMzYxMDJlMC02MjEzLTAxMzktMjA3OS0xYTI5YWM3Nzk0MTI=/export/properties/
Preview link: https://preview.sayduck.io/336102e0-6213-0139-2079-1a29ac779412

Product available on Customized Platform account.

**Comment by gabrielekraujelyte** [comment]
Can I get an update on this issue please?

**Comment by JoelSayduck** [comment]
Seems to be some ORM issue. Was able to fix the issue by enabling transforms on material and republishing the product.

Also, tested that duplicated product works.

Was not able to reproduce in staging. Let me know if this happens again.
