### ISSUE TITLE
3D scene issue

### ISSUE THREAD

**Issue by 3dproduction** [Sayduck/sayduck-platform-feedback#14]
Hi,
We are facing one issue in platform, in 3D scene we can't see any fabric, but in viewer there is fabric.
And whenever we are trying to upload new fabric here it behaves differently.

Can you help here?
I've attached platform link and screenshot with it.

https://platform.sayduck.com/editor/UHJvZHVjdC0zZGY4ZGZkMC00ZTk5LTAxMzktMmUxYi01ZTM5OTY4ZTNiMDc=/information/properties

![image](https://user-images.githubusercontent.com/87762015/128701994-a1810671-d47a-4c58-a516-1dcb9f53ab78.png)

**Comment by JoelSayduck** [comment]
Hi,

When working with a configurator, each part/configurator is loaded on top of the other. So if you can not see a node in the selected variant 3D scene, the node will be in another active variant 3D scene. 

On your reference product, there is a fabric mesh in the GP variant. Removing the fabric node from this variant will fix your issue.
