### ISSUE TITLE
Issue in published preview

### ISSUE THREAD

**Issue by 3dproduction** [Sayduck/sayduck-platform-feedback#15]
Hi,
Whenever we publishing this particular chair, we are facing one issue in published preview mode.
I've attached the image for this issue.
Please advise what to do.

Thank you.

![image](https://user-images.githubusercontent.com/87762015/128845250-4df63006-dab9-4650-a308-c5fbd0341424.png)
![image](https://user-images.githubusercontent.com/87762015/128845264-105c02a4-c8a2-4427-a225-0bbf7809e8e9.png)

**Comment by JoelSayduck** [comment]
Hi,

When experiencing occlusion map issues, try removing and adding back metalness, roughness or occlusion texture on the material. This will regenerate and fix the ORM map on the material.

Let me know if that does not fix the issue.
