### ISSUE TITLE
OBJ upload gives an error message

### ISSUE THREAD

**Issue by gabrielekraujelyte** [Sayduck/sayduck-platform-feedback#17]
When I upload an obj file to a new scene, I get the below error message

![image](https://user-images.githubusercontent.com/42536074/146737505-5d8aeb99-1023-4580-823d-21afa8aaf0b2.png)

I cannot attach the obj file on Github, do let me know I should send it over to you.

**Comment by JoelSayduck** [comment]
To attach assets, first zip it and then upload.

**Comment by gabrielekraujelyte** [comment]
[planter.zip](https://github.com/Sayduck/sayduck-platform-feedback/files/7744130/planter.zip)

**Comment by JoelSayduck** [comment]
Can not reproduce. Uploaded obj works.

[failed_obj.zip](https://github.com/Sayduck/sayduck-platform-feedback/files/7744952/failed_obj.zip)
