### ISSUE TITLE
Platform issue

### ISSUE THREAD

**Issue by 3dproduction** [Sayduck/sayduck-platform-feedback#6]
![image](https://user-images.githubusercontent.com/87762015/126485960-6c391567-bcf4-4736-a86e-beb5cadf922f.png)
Hi, 
We are trying to open any product link, we are facing mentioned issue.
We have attached image reference for the same.
Please help us resolving this issue.

Thank you.

**Comment by JoelSayduck** [comment]
Hi,

This issue occurs sometimes when you are trying to open a specific section in the Product. To avoid this issue, remove from the product URL everything after /information/properties/.

Example product URL:
https://platform.sayduck.com/editor/XXX123456789XXX123456789XXX123456789=/information/properties/

**Comment by 3dproduction** [comment]
Hi,
Great thank you so much for your information.
